### PR TITLE
docs(usage): updated usage instruction

### LINKED ISSUE #13: Updated README
Fix typo at 

```
"ghooks": {
  "precommit": "...", // should be pre-commit
  ...
}
```

May be the usage could be explained a bit more precisely, best would to point to an example project.

### PR DESCRIPTION
**Pull request by sarbbottam**
Fixes #13

### CODE REVIEW

**Comment by ta2edchimp** [comment]
This is great! Thank you!
Remember to add yourself to [`.all-contributorsrc`](https://github.com/ta2edchimp/opt-cli/blob/master/.all-contributorsrc) :wink: 

Do you think we should mention that it is also possible to put the opted-in/out rules into a `package.json`?

**Comment by sarbbottam** [comment]
> > Do you think we should mention that it is also possible to put the opted-in/out rules into a `package.json`?

The only reason I am skeptical about `package.json`, is that any changes to `package.json` might get checked in, during commit as its a tracked file.

Please correct me, I have misunderstood the usage.

**Comment by ta2edchimp** [comment]
Nope, that's correct.
Maybe we really should just skip mentioning `package.json` for the moment.

Would you add yourself to the `.all-contributorsrc`? I'd hit the merge button later (I'm only on my phone right now).

**Comment by sarbbottam** [comment]
@ta2edchimp done :smile:

**Pull request merged**
